-- REKT CLUB whitelist database — fresh setup
-- Run this once in Supabase SQL Editor.

create table if not exists public.whitelist_entries (
  id bigint generated by default as identity primary key,
  x_username text not null,
  wallet_address text not null,
  comment_url text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists whitelist_entries_x_username_unique
  on public.whitelist_entries (lower(x_username));

create unique index if not exists whitelist_entries_wallet_address_unique
  on public.whitelist_entries (lower(wallet_address));

create unique index if not exists whitelist_entries_comment_url_unique
  on public.whitelist_entries (lower(comment_url));

alter table public.whitelist_entries enable row level security;

-- No public INSERT/SELECT policies are intentionally created.
-- The website writes through the server-side /api/wl endpoint using the
-- Supabase secret/service-role credential stored only in Vercel.


-- Explicit API privileges.
-- The browser never talks to this table directly.
revoke all on table public.whitelist_entries from anon, authenticated;
grant select, insert, update, delete on table public.whitelist_entries to service_role;

-- Identity sequence used by the id column.
grant usage, select on sequence public.whitelist_entries_id_seq to service_role;
